#!/bin/bash
# Based on script by Robert Smith <quad at symbo1ics dot com>

PROG=$(basename "$0")

printUsage() {
cat << -EOF-
Usage:  $PROG  URL|CODE  [DIR]

  DIR:  optional directory to save to
  URL:  http://imgur.com/a/XXXXX[/all]
  CODE: XXXXX

Download images from an imgur album. When downloading, each dot represents a
downloaded image, while each space represents a preexisting and skipped image.

-EOF-
}

makeTemp() {
	local TEMPDIR
	if [ -d "$HOME/tmp" ]
	then TEMPDIR="$HOME/tmp"
	else TEMPDIR=/tmp
	fi
	mktemp -q --tmpdir="$TEMPDIR" "$PROG.$$.XXXX"
	if [ $? -ne 0 ]; then
		errorExit "Could not create temp file"
	fi
}
cleanUp() {
	rm -f "$DATA"
}
errorExit() {
	echo >&2 "$PROG: $@"
	cleanUp
	exit 3
}
trap "errorExit aborted" 2 3
trap "errorExit terminated" 1 15

if [ $# -eq 0 -o $# -gt 2 ]
then
	printUsage
	exit 2
fi

URL="${1%/}"
DIR="${2%/}"

if [[ "$URL" =~ ^[0-9A-Za-z]{5,}$ ]]; then
	URL="http://imgur.com/a/$URL/all"
elif [[ ! "$URL" =~ /all$ ]]; then
	URL+="/all"
fi

if [[ ! -d "$DIR" ]]; then
	DIR="$PWD"
fi

DATA=$(makeTemp)

declare -i code=0 p=1
declare -a list

while true; do
	curl -s "$URL?p=$p" >"$DATA"
	[ $? -ne 0 ] && errorExit "Page download error"

	proceed=
	for file in $(
		grep -P -o '"http://i.imgur.com/\w{5,}s\.\w{3}"' "$DATA" | \
		sed -e 's|"||g' -e 's|http://i.imgur.com/||' -e 's|s\.|.|'
	); do
		list+=("$file")
		proceed=1
	done

	if [ ! "$proceed" ]; then
		break
	else
		echo "Found page $p"
		p+=1
	fi
done

if (( p > 1 ))
then
	echo -n "Downloading ${#list[@]} images"

	for file in "${list[@]}"
	do
		if [ ! -f "$DIR/$file" ]
		then
			curl -s --create-dirs -o "$DIR/$file" "http://i.imgur.com/$file"
			if [ $? -eq 0 ]; then
				echo -n "."
			else
				echo -n "x"
				code+=1
			fi
		else
			echo -n " "
		fi
	done
	echo
	echo Done
fi

cleanUp
exit $code
