#!/bin/bash

rm -f	$HOME/.config/menus/applications-merged/wine*
rm -rf	$HOME/.local/share/applications/wine
rm -f	$HOME/.local/share/desktop-directories/wine*
# rm -f	$HOME/.local/share/icons/????_*.{xpm,png}
# rm -f	$HOME/.local/share/icons/*-x-wine-*.{xpm,png}
rm -rf	$HOME/.wine

type f &>/dev/null && f $HOME/.local/share/icons

exit 0
