#!/bin/bash
# base conversion

errorExit() {
	echo >&2 "Usage: $(basename "$0") [xdob][xdob] [ NUM... | -e RPN ]"
	echo >&2
	[ "$1" ] && echo >&2 "$(basename "$0"): $1"
	exit 2
}

if [ "$1" = "-e" ]
then eflag=1 && shift
else eflag=
fi

[ $# -eq 0 ] && errorExit

case "$1" in
	d?)	;;
	x?)	input="16i" ;;
	o?)	input="8i"  ;;
	b?)	input="2i"  ;;
	*)	errorExit "bad option" ;;
esac
case "$1" in
	?d)	;;
	?x)	input="16o$input" ;;
	?o)	input="8o$input"  ;;
	?b)	input="2o$input"  ;;
	*)	errorExit "bad option" ;;
esac
shift

if [ "$eflag" -o "$1" = "-e" ]; then
	shift
	if [ $# -gt 0 ];then
		input="$input $* p"
	fi
else
	while [ $# -gt 0 ]; do
		if [ $# -eq 1 ]
			then input="$input $1 p"
			else input="$input $1 n[ ]P"
		fi
		shift
	done
fi

expr="$(echo "$input" | tr 'a-f' 'A-F')"

if [ "$expr" != "$input" ]
then
	dc -e "$expr" | tr 'A-F' 'a-f'
else
	dc -e "$expr"
fi

# vim:set ts=4 sw=4 noet ft=sh:
