#!/bin/bash

opts=()

while [[ "$1" == -* ]]; do
	opts+=("$1")
	shift
done

if [ $# -eq 0 ]; then
	echo "${opts[@]}"
	exit
fi

case "$1" in
	r|red)		c=31 ;;
	g|green)	c=32 ;;
	y|yellow)	c=33 ;;
	b|blue)		c=34 ;;
	p|purple)	c=35 ;;
	c|cyan)		c=36 ;;
	*)			c=$1 ;;
esac
shift

if [[ ! "$c" =~ ^[0-9]+(,[0-9]+)?$ ]]; then
	echo >&2 "Usage: $(basename "$0") SPEC TEXT"
	echo >&2 "SPEC:  r[ed]  g[reen]  y[ellow]  b[lue]  p[urple]  c[yan]  FG[,BG]"
	exit 2
elif [[ "$c" =~ ^([0-9]+),([0-9]+)$ ]]; then
	c="${BASH_REMATCH[1]}"
	b=";${BASH_REMATCH[2]}"
else
	b=
fi

while [[ "$1" == -* ]]; do
	opts+=("$1")
	shift
done

echo -ne "\e[$c;1${b}m"
echo -n  "${opts[@]}" "$@"
echo -ne "\e[0m"

if [[ "${opts[*]}" != *n* ]]; then
	echo
fi

