#!/bin/bash

argv=()

while [[ "$1" == -* ]]; do
	argv+=("$1")
	shift
done

if [ $# -eq 0 ]; then
	echo "${argv[@]}"
	exit
fi

case "$1" in
	r|red)		c=31 ;;
	g|green)	c=32 ;;
	y|yellow)	c=33 ;;
	b|blue)		c=34 ;;
	p|purple)	c=35 ;;
	c|cyan)		c=36 ;;
	*)			c=$1 ;;
esac
shift

if [[ ! "$c" =~ ^[0-9]+$ ]]; then
	echo >&2 "Usage: $(basename "$0") " \
			 "r[ed] | g[reen] | y[ellow] | b[lue] | p[urple] | c[yan] | N  ..."
	exit 2
fi

echo -en "\e[$c;1m"
echo "${argv[@]}" "$@"
echo -en "\e[0m"
