#!/bin/bash

PROG=$(basename "$0")
IFS=$'\n'

DIR_PERM=0
FILE_PERM=0

printUsage() {
	echo "Usage: $PROG [-d MODE] [-f MODE] [-c] [-r] [-L] FILE..."
}

errorMsg() {
	if [ $# -gt 0 ]; then
		echo >&2 "$PROG: $@"
	fi
}

errorExit() {
	errorMsg "$@"
	exit 3
}
trap "errorExit aborted" 2 3
trap "errorExit terminated" 1 15

rflag=
Lflag=

if [ "$1" = "--help" ]; then
	printUsage
	exit 0
fi

while getopts 'hd:f:crRL' option
do
	case $option in
	h)		printUsage
			exit 0
			;;
	d)		DIR_PERM="$OPTARG"
			;;
	f)		FILE_PERM="$OPTARG"
			;;
	c)		DIR_PERM=755
			FILE_PERM=644
			;;
	r|R)	rflag=1
			;;
	L)		Lflag=-L
			;;
	?)		printUsage >&2
			exit 2
			;;
	esac
done
shift $((OPTIND - 1))

if [ $# -eq 0 -o -z "$FILE_PERM" -o -z "$DIR_PERM" ]; then
	printUsage >&2
	exit 2
elif [ "$FILE_PERM" = 0 -a "$DIR_PERM" = 0 ]; then
	errorMsg "Nothing to do"
	exit 0
fi

if   [[ "$FILE_PERM" != 0 && ! "$FILE_PERM" =~ ^[0-7]{3}$ && ! "$FILE_PERM" =~ ^[ugo]*[+-][rwx]+$ ]]; then
	errorExit "$FILE_PERM: Invalid file permission"
elif [[ "$DIR_PERM"  != 0 && ! "$DIR_PERM"  =~ ^[0-7]{3}$ && ! "$DIR_PERM"  =~ ^[ugo]*[+-][rwx]+$ ]]; then
	errorExit "$DIR_PERM: Invalid directory permission"
fi

PATH="${PATH#.:}"
PATH="${PATH%:.}"

declare -i code=0

recurse() {
	if [ "$DIR_PERM" != 0 ]; then
		find $Lflag "$1" -type d -execdir chmod "$DIR_PERM"  {} +
		[ $? -ne 0 ] && code+=1
	fi
	if [ "$FILE_PERM" != 0 ]; then
		find $Lflag "$1" -type f -execdir chmod "$FILE_PERM" {} +
		[ $? -ne 0 ] && code+=1
	fi
}

for arg in "$@"
do
	if [ -f "$arg" ]; then
		if [ "$FILE_PERM" != 0 ]; then
			chmod "$FILE_PERM" "$arg"
			[ $? -ne 0 ] && code+=1
		fi
	elif [ -d "$arg" ]; then
		if [ ! "$rflag" ]; then
			if [ "$DIR_PERM" != 0 ]; then
				chmod "$DIR_PERM" "$arg"
				[ $? -ne 0 ] && code+=1
			fi
		else
			if [ -r "$arg" ]; then
				recurse "$arg"
			else
				errorMsg "$arg: Permission denied"
				code+=1
			fi
		fi
	else
		errorMsg "$arg: No such file or directory"
		code+=1
	fi
done

exit $code

# vim:set ts=4 sw=4 noet ft=sh:
