#!/bin/bash

# system icon path
PRE="/usr/share/icons"

# possible png icon sizes
SIZES=(256 192 128 96 72 64 48 36 32 24 22 16)

if [ $# -lt 2 -o -z "$1" ]; then
	echo >&2 "Usage: $(basename "$0") [$PRE/]THEME SVG..."
	exit 2
elif [ -d "$1" -a -f "$1/index.theme" ]; then
	THEME="${1%/}" && shift
elif [ -d "$PRE/$1" -a -f "$PRE/$1/index.theme" ]; then
	THEME="$PRE/${1%/}" && shift
else
	echo >&2 "$1: Theme not found"
	exit 1
fi

set -- "${@%.svg}"
sudo echo -n || exit

declare -i code=0

DIM_PAT='\(^\|[[:blank:]]\)%="\([1-9][0-9]*\(\.[0-9]\+\)\?\)\(pt\)\?"'
WID_PAT=$(echo "$DIM_PAT" | sed 's/%/width/')
HGT_PAT=$(echo "$DIM_PAT" | sed 's/%/height/')

for name in "$@"; do
	svg="$name.svg"
	png="$name.png"

	if [ ! -f "$svg" -o ! -r "$svg" ]; then
		echo >&2 "ERROR: $svg not accessible"
		echo >&2
		code+=1
	else

		dir="$THEME/scalable"
		if [ -d "$dir" ]; then
			dest=$(find "$dir" -name "$(basename "$svg")")
			if [ -f "$dest" ]; then
				echo cp "$svg" "$dest"
				sudo cp "$svg" "$dest" || code+=1
			else
				echo >&2 "WARNING: $(basename "$svg") not found in $dir"
				code+=1
			fi
		fi

		x=$(grep -o "$WID_PAT" "$svg" | head -n 1 | sed 's/'"$WID_PAT"'/\2\4/')
		y=$(grep -o "$HGT_PAT" "$svg" | head -n 1 | sed 's/'"$HGT_PAT"'/\2\4/')
		if [ ! "$x" -o ! "$y" ]; then
			echo >&2 "ERROR: couldn't determine dimensions for $svg"
			echo >&2
			code+=1
			continue
		fi
		[[ "$x" == *pt ]] && x="(${x%pt}*1.25)"
		[[ "$y" == *pt ]] && y="(${y%pt}*1.25)"

		for size in "${SIZES[@]}"; do
			dir="$THEME/${size}x${size}"
			[ ! -d "$dir" ] && continue
			dest=$(find "$dir" -name "$(basename "$png")")
			if [ -f "$dest" ]; then
				xzoom=$(echo "scale=15; $size/$x" | bc)
				yzoom=$(echo "scale=15; $size/$y" | bc)
				if ! rsvg -x $xzoom -y $yzoom "$svg" "$png"; then
					code+=1
					continue
				fi
				echo cp "$png" "$dest"
				sudo cp "$png" "$dest" || code+=1
				rm "$png"
			else
				echo >&2 "WARNING: $(basename "$png") not found in $dir"
				code+=1
			fi
		done
		echo
	fi
done

exit $code
