#!/bin/bash

#########################################################################
#
#   Command-line timer
#
#   2009-08-26  File created
#
#########################################################################

PROG=$(basename "$0")
SOUND="$PROG.mp3"

printUsage() {
	echo "Usage: $PROG [-q] [H:]M[:S]"
}
errorUsage() {
	printUsage >&2
	exit 2
}

if [ "$1" = "--help" ]; then
	printUsage
	exit 0
fi
qflag=
while getopts 'h?q' option
do
	case $option in
	h|\?)	printUsage
			exit 0
			;;
	q)		qflag=1
			;;
	?)		errorUsage
			;;
	esac
done
shift $((OPTIND - 1))

errorExit() {
	[ ! "$qflag" ] && echo && date +'%T'
	echo >&2 "$PROG: $1"
	exit 1
}
trap "errorExit aborted" 2 3
trap "errorExit terminated" 1 15

NUM='([0-9]+(\.[0-9]*)?)'

if [ $# -eq 0 ]; then
	if [ ! "$qflag" ]; then
		date +'%T'
		sleep 60
		declare -i elapsed=1
		echo -n "$elapsed minute"
		while true; do
			sleep 60
			elapsed+=1
			echo -en "\r$elapsed minutes"
		done
	fi
	exit
elif [[ ! "$1" =~ ^$NUM?:?$NUM?:?$NUM?$ ]]; then
	errorUsage
fi

PARSE='{
	h = 0; s = 0;
	n = split($0, a, ":");
	if (n == 1) {
		m = a[1];
	} else if (n == 2) {
		m = a[1];
		s = a[2];
	} else if (n == 3) {
		h = a[1];
		m = a[2];
		s = a[3];
	} else
		exit 1;
	print int(h * 3600 + m * 60 + s);
}'

cd "$(dirname "$(readlink -f "$(which "$0")")")"

declare -i seconds=$(echo "$1" | awk "$PARSE")
[ $? -ne 0 ] && errorUsage

if [ "$qflag" ]; then
	sleep $seconds
	exit
fi

declare -i remaining=$seconds L=1200 D=600

if (( remaining > L )); then
	stops=($(( remaining % D )))
	if (( ${stops[0]} == 0 ))
	then stops=()
	else remaining+=-${stops[0]}
	fi
	while (( remaining > L )); do
		stops+=($D)
		remaining+=-$D
	done
else
	stops=()
fi

for s in 900 600 300 240 180 120 60 45 30 15 10 5 0; do
	if (( remaining > s )); then
		stops+=($(( remaining - s )))
		remaining=$s
	fi
done

STATUS='{
	if (! $0) exit;
	h = int($0 / 3600);
	if (h) {
		printf "%s hour%s", h, (h > 1 ? "s" : "");
		sep = " ";
	}
	$0 = $0 % 3600;
	m = int($0 / 60);
	if (m) {
		printf "%s%s minute%s", sep, m, (m > 1 ? "s" : "");
		sep = " ";
	}
	s = $0 % 60;
	if (s)
		printf "%s%s second%s", sep, s, (s > 1 ? "s" : "");
	printf " remaining";
}'

declare -i elapsed=0
date +'%T'
echo $seconds | awk "$STATUS" &

for s in "${stops[@]}"; do
	sleep $s
	elapsed+=$s
	tput el1 && echo -en "\r" &&
	echo $(( seconds - elapsed )) | awk "$STATUS" &
done

date +'%T'

qflag=1
if which mpg123 &>/dev/null && [ -f "$SOUND" ]; then
	mpg123 "$SOUND" &>/dev/null
fi
